config/routes.rb
Rails.application.routes.draw do
  resources :ios
  resources :profiles
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'control_panel#index'

  get '/control_panel', to: 'control_panel#index'

  resources :users do
    resources :devices
    resources :profiles, only: [:index, :new, :create]
  end

  resources :profiles, only: [:show, :edit, :update, :destroy] do
    resources :ios, only: [:index, :new, :create]
  end

  resources :ios, only: [:show, :edit, :update, :destroy] 
  get 'ios/:id/status', to: 'ios#status'
  post 'ios/:id', to: 'ios#trigger'

  put 'verify_pin', to: 'application#verify_pin'

end

app/models/device.rb
class Device < ApplicationRecord
	belongs_to :user
	has_many :io

	validates :name, :external_id, :user_id, presence: true
end

app/models/particle/device.rb
require 'rest-client'
require 'json'

module Particle
  class Device < Particle::Base
  	attr_accessor :external_id, :settings

  	def get_status
		response = self.send(self.settings["statusFunction"], { "arg": self.settings["statusPin"] })

# p "HI"
# p response["return_value"] == 1
# p response["return_value"].to_i == 1

		status = !(response && response["return_value"] && response["return_value"] == 1)
  		{io_status: status}
  	end

  	def trigger(action)
		response = self.send(action, { "arg": self.settings["statusPin"] })
  	end

  	def send(action, args)
  		response = RestClient.post("https://api.particle.io/v1/devices/#{self.external_id}/#{action}", 
  			args, 
  			{"Authorization": "Bearer " + token })
		response_json = JSON.parse(response.body)
  	end

  end
end

app/controllers/devices_controller.rb
class DevicesController < AuthenticatedController
  load_and_authorize_resource :user
  # load_resource :user
  load_and_authorize_resource :device, :through => :user

  # before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    # @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    @device.user_id = @device.user_id || current_user.id

    respond_to do |format|
      if @device.save
        format.html { redirect_to new_user_device_path(current_user), notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to new_user_device_path(current_user), notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.fetch(:device, {}).permit!
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.haml
= form_for @device, url: user_devices_path(current_user) do |f|
  - if notice
    .alert.alert-success= notice
  - if @device.errors.any?
    .alert.alert-danger
      %h2= "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      %ul
        - @device.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-xs-12
      %legend DEVICES
      %table.table.table-striped
        %tbody
          - current_user.devices.each do |device|
            %tr
              %td{:valign => "center", :style => "vertical-align:middle"} #{device.name} - #{device.external_id}
              %td 
                = link_to user_device_path(current_user, device), :class => "btn btn-danger pull-right", data: {:confirm => 'Are you sure?'}, :method => :delete do
                  %i.fa.fa-trash
            
        %tfoot
          %tr 
            %td{:colspan => 2}
              %br
              .form-group
                = f.text_field :name, :class => "form-control", :placeholder => "Device Name"
              .form-group
                = f.text_field :external_id, :class => "form-control", :placeholder => "Device ID"
              = f.submit 'Save', :class => 'btn btn-primary'

app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%h1 Listing devices

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @devices.each do |device|
      %tr
        %td= link_to 'Show', device
        %td= link_to 'Edit', edit_device_path(device)
        %td= link_to 'Destroy', device, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Device', new_device_path

app/views/devices/new.html.haml
= render 'form'

app/views/devices/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path