config/routes.rb
Rails.application.routes.draw do
  resources :ios
  resources :profiles
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'control_panel#index'

  get '/control_panel', to: 'control_panel#index'

  resources :users do
    resources :devices
    resources :profiles, only: [:index, :new, :create]
  end

  resources :profiles, only: [:show, :edit, :update, :destroy] do
    resources :ios, only: [:index, :new, :create]
  end

  resources :ios, only: [:show, :edit, :update, :destroy] 
  get 'ios/:id/status', to: 'ios#status'
  post 'ios/:id', to: 'ios#trigger'

  put 'verify_pin', to: 'application#verify_pin'

end

app/models/io.rb
require 'json'

class Io < ApplicationRecord
	has_and_belongs_to_many :profiles
	belongs_to :device

	validates :name, :io_type, presence: true

	def settings_json
		JSON.parse(self.settings)
	end
end

app/controllers/ios_controller.rb
class IosController < AuthenticatedController
  # load_and_authorize_resource :profile
  # load_and_authorize_resource :io, :through => :profile

  before_action :set_io, :except => [:index, :new, :create]

  load_resource :profile, :only => [:index, :new, :create]
  load_resource :io, :through => :profile, :only => [:index, :new, :create]

  authorize_resource :profile, :only => [:index, :new, :create]
  authorize_resource :io

  # load_and_authorize_resource :profile, :only => [:index, :new, :create]
  # load_and_authorize_resource :io, :through => :profile, :only => [:index, :new, :create]

  

  # GET /ios
  # GET /ios.json
  def index
    @ios = Io.all
  end

  # GET /ios/1
  # GET /ios/1.json
  def show
  end

  # GET /ios/new
  def new
    @io = Io.new
  end

  # GET /ios/1/edit
  def edit
  end

  # POST /ios
  # POST /ios.json
  def create
    @io = Io.new(io_params)

    respond_to do |format|

      @profile.ios << @io

      if @io.save
        format.html { redirect_to @io, notice: 'Io was successfully created.' }
        format.json { render :show, status: :created, location: @io }
      else
        format.html { render :new }
        format.json { render json: @io.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ios/1
  # PATCH/PUT /ios/1.json
  def update
    respond_to do |format|
      if @io.update(io_params)
        format.html { redirect_to @io, notice: 'Io was successfully updated.' }
        format.json { render :show, status: :ok, location: @io }
      else
        format.html { render :edit }
        format.json { render json: @io.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ios/1
  # DELETE /ios/1.json
  def destroy
    @io.destroy
    respond_to do |format|
      format.html { redirect_to ios_url, notice: 'Io was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def status
    particle_device = Particle::Device.new(external_id: @io.device.external_id, settings: @io.settings_json)
    render json: particle_device.get_status
  end

  def trigger
    particle_device = Particle::Device.new(external_id: @io.device.external_id, settings: @io.settings_json)
    render json: particle_device.trigger(params["actionFunction"])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_io
      @io = Io.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def io_params
      io_params_hash = params.fetch(:io, {}).permit!

      io_params_hash[:settings] = io_params_hash[:settings].to_json
      p io_params_hash
    end
end

app/helpers/ios_helper.rb
module IosHelper
end

app/views/ios/_form.html.haml
= form_for @io do |f|
  - if @io.errors.any?
    #error_explanation
      %h2= "#{pluralize(@io.errors.count, "error")} prohibited this io from being saved:"
      %ul
        - @io.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/ios/edit.html.haml
%h1 Editing io

= render 'form'

= link_to 'Show', @io
\|
= link_to 'Back', ios_path

app/views/ios/index.html.haml
%h1 Listing ios

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @ios.each do |io|
      %tr
        %td= link_to 'Show', io
        %td= link_to 'Edit', edit_io_path(io)
        %td= link_to 'Destroy', io, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Io', new_io_path

app/views/ios/new.html.haml
%h1 New io

= render 'form'

= link_to 'Back', ios_path

app/views/ios/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_io_path(@io)
\|
= link_to 'Back', ios_path