config/routes.rb
Rails.application.routes.draw do
  resources :ios
  resources :profiles
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'control_panel#index'

  get '/control_panel', to: 'control_panel#index'

  resources :users do
    resources :devices
    resources :profiles, only: [:index, :new, :create]
  end

  resources :profiles, only: [:show, :edit, :update, :destroy] do
    resources :ios, only: [:index, :new, :create]
  end

  resources :ios, only: [:show, :edit, :update, :destroy] 
  get 'ios/:id/status', to: 'ios#status'
  post 'ios/:id', to: 'ios#trigger'

  put 'verify_pin', to: 'application#verify_pin'

end

app/views/layouts/_head_layout.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title>ParticleFire</title>
	<%= csrf_meta_tags %>

	<%= render 'layouts/head_layout' %>
  </head>

  <body class="body-main">

	<div class="navbar navbar-default navbar-fixed-top">
	  <div class="container-fluid">
		<div class="navbar-header"><a id="brand" class="navbar-brand"><span>particle</span><span class="white">Fire</span><i class="primary-color fa fa-fire"></i></a></div>
		<div class="navbar-collapse collapse">

			<%- if current_user %>
				<ul class="nav navbar-nav">
					<li><a href="/">Home</a></li>
					<li>
						<a href="/users/edit"><i class="fa fa-gear"></i>&nbsp;
							Settings
						</a>
					<li>
						<%= link_to new_user_device_path(current_user) do %>
							<i class="fa fa-user"></i>&nbsp;Devices
						<% end %>
					</li>
					</li>
					<%- if current_user.master_admin %>
						<li>
							<a href="/admin/users"><i class="fa fa-user"></i>&nbsp;
								Users
							</a>
						</li>
					<%- end %>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					<li>
						<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
					</li>
				</ul>
				<p class="navbar-text navbar-right">Welcome <%= current_user.email %></p>
			<%- else %>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="/">Sign In </a></li>
				</ul>
			<%- end %>

		</div>
	  </div>
	</div>
	<div id="main" class="container-fluid container-main">

		<%= yield %>

	</div>

	<div class="footer-wrapper">
	  <div class="footer-content">
		<p>
		  &copy; 2016
		  &nbsp;<a class="light-grey">Brad Carlson</a>
		</p>
	  </div>
	</div>

  </body>
</html>

app/views/layouts/basic.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParticleFire</title>
    <%= csrf_meta_tags %>

    <%= render 'layouts/head_layout' %>
  </head>

  <body>

    <%= yield %>

    <div class="footer-wrapper">
      <div class="footer-content">
        <p>
          &copy; 2016
          &nbsp;<a class="light-grey">Brad Carlson</a>
        </p>
      </div>
    </div>


  </body>
</html>